import crypto from 'crypto';

const ALGORITHM = 'aes-256-gcm';
// Ensure ENCRYPTION_KEY is provided in the environment variables and is 64 hex characters (32 bytes)
function getEncryptionKey(): Buffer {
  const encryptionKeyHex = process.env.ENCRYPTION_KEY;

  if (!encryptionKeyHex || !/^[0-9a-fA-F]{64}$/.test(encryptionKeyHex)) {
    throw new Error('ENCRYPTION_KEY must be exactly 32 bytes (64 hexadecimal characters)');
  }

  return Buffer.from(encryptionKeyHex, 'hex');
}

/**
 * Encrypts a text string using AES-256-GCM.
 * @param text The text to encrypt
 * @returns A string in the format "iv:authTag:encryptedHex"
 */
export function encrypt(text: string): string {
  if (!text) return text;
  
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv(ALGORITHM, getEncryptionKey(), iv);
  
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  
  const authTag = cipher.getAuthTag();
  
  return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted}`;
}

/**
 * Decrypts a hash string generated by the encrypt function.
 * @param hash The encrypted string in the format "iv:authTag:encryptedHex"
 * @returns The decrypted text string
 */
export function decrypt(hash: string): string {
  if (!hash) return hash;
  
  try {
    const parts = hash.split(':');
    if (parts.length !== 3) throw new Error('Invalid encrypted format');
    
    const [ivHex, authTagHex, encryptedHex] = parts;
    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');
    
    const decipher = crypto.createDecipheriv(ALGORITHM, getEncryptionKey(), iv);
    decipher.setAuthTag(authTag);
    
    let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    
    return decrypted;
  } catch (error) {
    console.error('Decryption failed:', error);
    throw new Error('Decryption failed');
  }
}

/**
 * Encrypts sensitive lead information (PII).
 * @param data An object containing phone and email
 * @returns An object with the phone and email encrypted
 */
export function encryptLeadPII(data: { phone: string; email: string }): { phone: string; email: string } {
  return {
    phone: data.phone ? encrypt(data.phone) : data.phone,
    email: data.email ? encrypt(data.email) : data.email,
  };
}

/**
 * Decrypts sensitive lead information (PII).
 * @param data An object containing encrypted phone and email
 * @returns An object with the phone and email decrypted
 */
export function decryptLeadPII(data: { phone: string; email: string }): { phone: string; email: string } {
  return {
    phone: data.phone ? decrypt(data.phone) : data.phone,
    email: data.email ? decrypt(data.email) : data.email,
  };
}
